name: btap_batch
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0=py38haa244fe_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h294d835_2
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - autograd=1.3=py_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.3.0=pyh44b312d_0
  - boto3=1.17.25=pyhd8ed1ab_0
  - botocore=1.20.25=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h294d835_1001
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py38haa244fe_1
  - cffi=1.14.5=py38hd8c33c5_0
  - chardet=4.0.0=py38haa244fe_1
  - cma=2.7.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.6=py38hd7da0ea_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-py=4.4.4=py38haa244fe_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - et_xmlfile=1.0.1=py_1001
  - freetype=2.10.4=h546665d_1
  - future=0.18.2=py38haa244fe_3
  - icu=67.1=h33f27b4_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.2=py38haa244fe_0
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py38hc5df569_1
  - ipython=7.21.0=py38hc5df569_0
  - ipython_genutils=0.2.0=py_1
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py38haa244fe_2
  - jinja2=2.11.3=pyh44b312d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py38haa244fe_0
  - jupyter_server=1.4.1=py38haa244fe_0
  - jupyterlab=3.0.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38hbd9d945_1
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=10.0.1=default_hf44288c_1
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=h1d00b33_2
  - libpq=13.1=h4f54205_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=hc10be44_0
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38h294d835_3
  - matplotlib=3.3.4=py38haa244fe_0
  - matplotlib-base=3.3.4=py38h34ddff4_0
  - mistune=0.8.4=py38h294d835_1003
  - mkl=2020.4=hb70f87d_311
  - msys2-conda-epoch=20160418=1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38haa244fe_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py38haa244fe_0
  - numpy=1.20.1=py38h0cc643e_0
  - olefile=0.46=pyh9f0ad1d_1
  - openpyxl=3.0.7=pyhd8ed1ab_0
  - openssl=1.1.1j=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38h4c96930_0
  - pandoc=2.12=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38h9273828_0
  - pip=21.0.1=py38haa95532_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - psycopg2=2.8.6=py38hd8c33c5_2
  - pyaml=20.4.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38haa244fe_7
  - pyqt-impl=5.12.3=py38h885f38d_7
  - pyqt5-sip=4.19.18=py38h885f38d_7
  - pyqtchart=5.12=py38h885f38d_7
  - pyqtwebengine=5.12.1=py38h885f38d_7
  - pyrsistent=0.17.3=py38h294d835_2
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.8=hdbf39b2_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=227=py38h294d835_1
  - pywinpty=0.5.7=py38h32f6830_1
  - pyyaml=5.4.1=py38h294d835_0
  - pyzmq=22.0.3=py38h09162b1_1
  - qt=5.12.9=hb2cf2c5_0
  - requests=2.25.1=pyhd3deb0d_0
  - s3transfer=0.3.4=pyhd8ed1ab_0
  - scikit-learn=0.24.1=py38ha09990b_0
  - scipy=1.6.0=py38h5f893b4_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=pyh9f0ad1d_0
  - sniffio=1.2.0=py38haa244fe_1
  - sqlalchemy=1.3.23=py38h294d835_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.2=py38haa244fe_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py38h294d835_1
  - traitlets=5.0.5=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py38haa244fe_4
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - pymoo==0.4.2.2
prefix: C:\Users\plopez\Miniconda3\envs\btap_batch
