# based on install commands:
# conda create --prefix ./envs python=3.9
# conda install -c conda-forge boto3 conda dash dash-core-components dash-html-components dash-renderer dash-table docker-py icecream openpyxl pandas pip plotly psycopg2 pyyaml scikit-learn scikit-optimize sqlalchemy
# pip install pymoo dash-bootstrap-components

#packages and depencies locked versions below.
# conda env create --prefix ./env --file environment.yml
#List lock versions
# conda env export
name: btap_batch
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - boto3=1.18.49=pyhd8ed1ab_0
  - botocore=1.21.49=pyhd8ed1ab_0
  - brotli-python=1.0.9=py39h415ef7b_5
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py39hcbf5309_0
  - cffi=1.14.6=py39h0878f49_1
  - chardet=4.0.0=py39hcbf5309_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py39hcbf5309_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.10.3=py39hcbf5309_2
  - conda-package-handling=1.7.3=py39hb3671d1_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - cycler=0.10.0=py_2
  - dash=2.0.0=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_0
  - dash-html-components=2.0.0=pyhd8ed1ab_0
  - dash-renderer=1.9.1=pyhd8ed1ab_0
  - dash-table=5.0.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - docker-py=5.0.2=py39hcbf5309_0
  - docker-pycreds=0.4.0=py_0
  - et_xmlfile=1.0.1=py_1001
  - executing=0.8.1=pyhd8ed1ab_0
  - flask=2.0.1=pyhd8ed1ab_0
  - flask-compress=1.10.1=pyhd8ed1ab_0
  - freetype=2.10.4=h546665d_1
  - greenlet=1.1.1=py39h415ef7b_0
  - icecream=2.1.1=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h8d14728_2003
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.2=py39h2e07f2f_0
  - krb5=1.19.2=hbae68bd_2
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=11_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libpq=13.3=hfcc5ef8_0
  - libtiff=4.3.0=h0c97f57_1
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39hb82d6ee_0
  - matplotlib-base=3.4.3=py39h581301d_1
  - menuinst=1.4.18=py39hcbf5309_0
  - mkl=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - numpy=1.21.2=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py39h2e25243_0
  - pillow=8.3.2=py39h916092e_0
  - pip=21.2.4=pyhd8ed1ab_0
  - plotly=5.3.1=pyhd8ed1ab_0
  - psycopg2=2.9.1=py39h0878f49_0
  - pyaml=20.4.0=pyh9f0ad1d_0
  - pycosat=0.6.3=py39hb82d6ee_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=227=py39hb82d6ee_1
  - pyyaml=5.4.1=py39hb82d6ee_1
  - requests=2.26.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py39hb82d6ee_1004
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - scikit-learn=1.0=py39h74df8f2_1
  - scikit-optimize=0.8.1=pyh9f0ad1d_0
  - scipy=1.7.1=py39hc0c34ad_0
  - setuptools=58.0.4=py39haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.25=py39hb82d6ee_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2021.3.0=h2d74725_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tk=8.6.11=h8ffe710_1
  - tornado=6.1=py39hb82d6ee_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - websocket-client=0.57.0=py39hcbf5309_4
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39h2bbff1b_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
  - pip:
    - autograd==1.3
    - cma==2.7.0
    - dash-bootstrap-components==1.0.0b3
    - future==0.18.2
    - pymoo==0.5.0
